### ISSUE TITLE
Definition order

### ISSUE THREAD

**Issue by chillenzer** [edbennett/format_multiple_errors#12]
You might want to have a consistent order of function definitions, e.g., the order they are used in. Also, in Python you would have the option to define them actually in the order they are used in so that the reader can actually read the file from top to bottom (as opposed to many compiled languages where you have to reverse that order because the compiler must be aware of the function at the time of usage). Is a matter of taste and might confuse some that come from other languages but without previous bias I'd say that's the nicest way for the reader.

**Comment by chillenzer** [comment]
Unless that is deterministically reproducible and accessible to the reader at the time of reading the code. You might want to start uploading your mind to the internet.

**Comment by edbennett** [comment]
Brb, changing my name to Kusanagi Motoko.

**Comment by chillenzer** [comment]
"A strong-willed, physically powerful, and highly intelligent [cyberhero](https://en.wikipedia.org/wiki/Cyberhero)" (from Wikipedia) -- I'm happy that impostor syndrome and lacking self-esteem are no issues for you.

**Comment by chillenzer** [comment]
Okay, my two-minutes-on-wikipedia expertise on this character is insufficient to provide me with a quick-witted reaction.

**Comment by edbennett** [comment]
Gave up on uploading my mind to the internet, and instead reordered functions such that they in principle read top to bottom (at least as consistently as I can define that given the code structure)

There might be some benefit to factoring out some functions to a separate module (300 lines isn't massive, but is starting to get a little on the long side), but that's out of scope for this issue.
