### ISSUE TITLE
`_first_digit` oneliner

### ISSUE THREAD

**Issue by chillenzer** [edbennett/format_multiple_errors#13]
Just for the fun of it: [This](https://github.com/edbennett/format_multiple_errors/blob/e91718f5269ffe724047808599051ca1664e28d9/format_multiple_errors/formatter.py#L86) could be a oneliner:
```python3
return value or int(math.floor(math.log10(abs(value))))
```
You should close this issue immediately as not planned but I just liked the finding. =)

**Comment by edbennett** [comment]
It could be a one-liner, but not _that_ oneliner.

    return value and int(math.floor(math.log10(abs(value))))

Which is exactly why I won't change it to that—I always get confused reading code that uses `and` and `or` like this, and have to carefully unpick it, whereas the intent of the current explicit version is clear, I think.
